### PR TITLE
chore: fix typos and rewrite some expressions in English language; rename Chinese (Simplified) language

### PR DESCRIPTION
**Pull request by Naptie**
Browsing my site powered by SYZOJ-NG in English language, I discovered a few typos and some expressions that may not meet OCD standards. Therefore, I forked this repo and managed to fix typos and rewrite some expressions. To sum up, I changed the strings in English translation that:

1. contain typos
2. contain obvious grammar mistakes
3. contain unlocalized expressions
4. are verb phrases but the first letter of each word is capitalized (e.g. "Make Public" -> "Make public"; "No Permission" -> "No permission", as "no" is considered the abbreviation of "not have")
5. are not verb phrases but the first letters of the words are not all capitalized (e.g. "Last updated" -> "Last Updated")

(Note: I'm not sure if all strings with problems mentioned above have been fixed)

In addition, I found that because the Chinese (Simplified) language has brackets in its name, it doesn't look well when displayed with expressions such as "浏览器默认（{name}）". In order to solve this problem, I renamed this language from "Chinese (Simplified)" to "Simplified Chinese" (also in zh-CN: "中文（简体）" -> "简体中文"; in ja-JP: "中国語（簡体）" -> "簡体字中国語").

### CODE REVIEW

**Comment by Menci** [comment]
Please change `Private` back to `Non-public`.

A `Non-public` problem is something **not yet** set to public, not for **private** usage.

**Comment by t123yh** [comment]
卧槽，为啥要一个一个文件commit，为啥不把所有东西放到一个commit里面？而且还一个一个分开推送，邮箱都快炸了

**Comment by Naptie** [comment]
> 卧槽，为啥要一个一个文件commit，为啥不把所有东西放到一个commit里面？而且还一个一个分开推送，邮箱都快炸了

emm 我是直接在网页上修改文件的（懒得离线下来了）

其实您完全可以ignore掉这个pr的

**Comment by t123yh** [comment]
> 其实您完全可以ignore掉这个pr的

好的，我已经 ignore，你可以继续

**Pull request closed without merging**
